logging:
  file:
    path: logs/reseptron_pharmacy_service.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    root: info
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR